(1-3)既に登録されているメールアドレスを登録しようとすると、エラーを出力するように変更しました。
RakusPartners/ex-emp-management-bugfix-kudo pull request #7
Opened 2024-05-27 07:00 UTC by tokushikudo

よろしくお願いします。

2024-05-27 23:51 UTC, blitzkrieg1219 commented on src/main/resources/templates/administrator/insert.html
> +                      <div th:if="${mailRegisterError != null}" style="color:red">
CSS効かせるためにも、class追加してもいいかも

class="error-messages"

2024-05-27 23:54 UTC, blitzkrieg1219 commented on src/main/java/com/example/controller/AdministratorController.java
> +            String mailError = "入力されたメールアドレスは既に登録されています";
修正の保存前にインデントはきれいにしましょう。
メソッドの終端を見間違えたり、思わぬ不具合を招く可能性があります。

https://fineworks-fine.hatenablog.com/entry/2023/01/12/073000

2024-05-27 23:55 UTC, blitzkrieg1219 requested changes
確認しました。
指摘事項の対応をお願いします。

2024-05-28 03:30 UTC, tokushikudo commented
インデント修正とCSS追加が完了しました。
ご確認お願いします。

2024-05-28 04:51 UTC, merged